name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    name: GolangCI Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: go test ./internal/...

  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: sh build.sh

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Migrations
        run: ./env/migrate/build.sh

      - name: Build Services
        run: ./build.sh

      - name: Set up Test Environment
        run: ./env/env.sh up

      - name: Run Database Tests
        run: go test -tags integration ./internal/app/apiserver/internal/store/store_test.go -v

      - name: Run Integration Tests
        run: go test -tags integration ./tests/... -v
